### ISSUE TITLE
pages: create proper content/css to about page

### ISSUE THREAD

**Issue by virgilio** [hacklabr/viradapp#19]

**Comment by brunosmartin** [comment]
Pegar conteúdo com o Instituto TIM

**Comment by brunosmartin** [comment]
Bruno,
Tudo bem?

Segue o texto "sobre" para o aplicativo da Virada Cultural. 
Peço que hyperlink a página do Mapas Culturais, no site do Instituto TIM e a página do SP Cultura. 

Qualquer dúvida, manda um alô

Beijo

Aplicativo criado com base nos dados do SP Cultura, uma instalação do software livre para mapeamento colaborativo e gestão da cultura Mapas Culturais  - desenvolvido pelo Instituto TIM em parceria com a Secretaria da Cultura do Município de São Paulo. A ferramenta está alinhada ao Sistema Nacional de Indicadores e Índices Culturais (SNIIC) e à Lei de Acesso à Informação.

Em 2015, o Instituto TIM celebra dois anos de parceria com o município de São Paulo e dois anos de atuação, desenvolvendo tecnologias livres para dar mais qualidade à gestão e visibilidade a ações, políticas e programas públicos como a Virada Cultural de São Paulo.
