### ISSUE TITLE
Criar imagem "Gráfico de recurso" para loja Google plai

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/viradapp#25]
https://support.google.com/googleplay/android-developer/answer/1078870?hl=pt-BR

**Comment by catkit** [comment]
![google-play-featured-image](https://cloud.githubusercontent.com/assets/3521683/7923058/b5f5665a-0886-11e5-9733-5c0808ad3a25.png)

**Comment by catkit** [comment]
Mandei no email.
